# Importação de bibliotecas
from core.base.base_repository import BaseRepository
from api.v1.packages.companies.schemas.companies_schema import CompanySchemaBase


class CreateCompany(BaseRepository):
    def execute(self, company: CompanySchemaBase):
        # Realiza a inserção do registro
        self.cursor.execute(
            """
                    INSERT INTO companies (company_id,
                                           situation_id,
                                           nickname,
                                           name_business,
                                           name_fantasy,
                                           cnpj,
                                           cns,
                                           site,
                                           telephone,
                                           cellphone,
                                           email,
                                           password,
                                           responsible,
                                           responsible_office,
                                           cep,
                                           state_id,
                                           city_id,
                                           district,
                                           complement,
                                           expiration_day,
                                           value_monthly,
                                           stations,
                                           start_contract,
                                           first_payment,
                                           history,
                                           date_register,
                                           date_update)
                    VALUES (%s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s,
                            %s)
                    """,
            (
                company.company_id,
                company.situation_id,
                company.nickname,
                company.name_business,
                company.name_fantasy,
                company.cnpj,
                company.cns,
                company.site,
                company.telephone,
                company.cellphone,
                company.email,
                company.password,
                company.responsible,
                company.responsible_office,
                company.cep,
                company.state_id,
                company.city_id,
                company.district,
                company.complement,
                company.expiration_day,
                company.value_monthly,
                company.stations,
                company.start_contract,
                company.first_payment,
                company.history,
                company.date_register,
                company.date_update,
            ),
        )

        # Realiza o commit da transação
        self.commit()
        return True
